#!/usr/bin/env bash
c=1;
while [[ c -lt 21 ]]; 
do
case $c in
4 )
echo $c
echo "bad luck from China";;
9 )
echo $c
echo "bad luck from Japan";;
17 )
echo $c
echo "bad luck from Italy";;
20 )
echo $c
echo "sylvain@ubuntu$";;
*)
echo "$c";;
esac
c=$((c+1));
done
